import torch

SEED = 666
SAVE_IMG = 1

CHECKPOINT = ''
LOGS = ''

PARSING_ROOT = ''
LANDMARK_ROOT = ''
IMG_ROOT = ''
RESULT = './result'

EPOCHS = 100
BATCH_SIZE = 1
NUM_WORKERS = 8
MILESTONES = [30, 60, 90]

LR = 0.01
WD = 1e-5
BETA1 = 0.5
BETA2 = 0.999

DEVICE = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")

RESUME_COARSE = ''
RESUME_ENCODER = ''
RESUME_DECODER = ''
RESUME_PRIOR_ESTIMATION = ''

RESUME_OPTIM_COARSE = ''
RESUME_OPTIM_PRIOR_ESTIMATION = ''
RESUME_OPTIM_ENCODER = ''
RESUME_OPTIM_DECODER = ''
RESUME_OPTIM_ENCODER_DECODER = ''
